# Generated by Django 3.2.8 on 2024-11-23 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='tipo_gasto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.tipogasto', verbose_name='TipoGasto'),
        ),
    ]
