# Generated by Django 3.2.8 on 2024-11-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_gasto_tipo_gasto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='motivo_cancelacion',
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha_registro',
            field=models.DateField(editable=False),
        ),
    ]
