# Generated by Django 3.2.8 on 2024-11-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_pago_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentabancaria',
            name='num_cuenta',
            field=models.BigIntegerField(),
        ),
    ]
